/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BeanBlockTrackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addCarbonEntry"
      | "batchInitialized"
      | "getHistoryCount"
      | "getTotalCarbon"
      | "history"
      | "initializeBatch"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CarbonAdded"): EventFragment;

  encodeFunctionData(
    functionFragment: "addCarbonEntry",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "batchInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHistoryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCarbon",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "history",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeBatch",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addCarbonEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHistoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCarbon",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "history", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeBatch",
    data: BytesLike
  ): Result;
}

export namespace CarbonAddedEvent {
  export type InputTuple = [
    stage: BigNumberish,
    carbon: BigNumberish,
    documentHash: string
  ];
  export type OutputTuple = [
    stage: bigint,
    carbon: bigint,
    documentHash: string
  ];
  export interface OutputObject {
    stage: bigint;
    carbon: bigint;
    documentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BeanBlockTracker extends BaseContract {
  connect(runner?: ContractRunner | null): BeanBlockTracker;
  waitForDeployment(): Promise<this>;

  interface: BeanBlockTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCarbonEntry: TypedContractMethod<
    [stage: BigNumberish, carbon: BigNumberish, documentHash: string],
    [void],
    "nonpayable"
  >;

  batchInitialized: TypedContractMethod<[], [boolean], "view">;

  getHistoryCount: TypedContractMethod<[], [bigint], "view">;

  getTotalCarbon: TypedContractMethod<[], [bigint], "view">;

  history: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint] & {
        stage: bigint;
        carbon: bigint;
        documentHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  initializeBatch: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCarbonEntry"
  ): TypedContractMethod<
    [stage: BigNumberish, carbon: BigNumberish, documentHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getHistoryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalCarbon"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "history"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint] & {
        stage: bigint;
        carbon: bigint;
        documentHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initializeBatch"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CarbonAdded"
  ): TypedContractEvent<
    CarbonAddedEvent.InputTuple,
    CarbonAddedEvent.OutputTuple,
    CarbonAddedEvent.OutputObject
  >;

  filters: {
    "CarbonAdded(uint8,uint256,string)": TypedContractEvent<
      CarbonAddedEvent.InputTuple,
      CarbonAddedEvent.OutputTuple,
      CarbonAddedEvent.OutputObject
    >;
    CarbonAdded: TypedContractEvent<
      CarbonAddedEvent.InputTuple,
      CarbonAddedEvent.OutputTuple,
      CarbonAddedEvent.OutputObject
    >;
  };
}
