/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mytokenSol from "./Mytoken.sol";
export type { mytokenSol };
export type { BeanBlockTracker } from "./BeanBlockTracker";
export type { TradeDocuments } from "./TradeDocuments";
