/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TradeDocumentsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getCarbonEmission"
      | "getDocument"
      | "isProductComplete"
      | "owner"
      | "renounceOwnership"
      | "setCarbonEmission"
      | "storeDocument"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DocumentStored" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getCarbonEmission",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDocument",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isProductComplete",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCarbonEmission",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "storeDocument",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCarbonEmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProductComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCarbonEmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DocumentStoredEvent {
  export type InputTuple = [
    productId: BigNumberish,
    docType: BigNumberish,
    cid: string,
    uploadedBy: AddressLike
  ];
  export type OutputTuple = [
    productId: bigint,
    docType: bigint,
    cid: string,
    uploadedBy: string
  ];
  export interface OutputObject {
    productId: bigint;
    docType: bigint;
    cid: string;
    uploadedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TradeDocuments extends BaseContract {
  connect(runner?: ContractRunner | null): TradeDocuments;
  waitForDeployment(): Promise<this>;

  interface: TradeDocumentsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCarbonEmission: TypedContractMethod<
    [productId: BigNumberish],
    [
      [bigint, string, string, bigint] & {
        totalEmissions: bigint;
        unit: string;
        reportedBy: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getDocument: TypedContractMethod<
    [productId: BigNumberish, docType: BigNumberish],
    [
      [string, string, bigint] & {
        cid: string;
        uploadedBy: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  isProductComplete: TypedContractMethod<
    [productId: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setCarbonEmission: TypedContractMethod<
    [productId: BigNumberish, totalEmissions: BigNumberish, unit: string],
    [void],
    "nonpayable"
  >;

  storeDocument: TypedContractMethod<
    [productId: BigNumberish, docType: BigNumberish, cid: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCarbonEmission"
  ): TypedContractMethod<
    [productId: BigNumberish],
    [
      [bigint, string, string, bigint] & {
        totalEmissions: bigint;
        unit: string;
        reportedBy: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDocument"
  ): TypedContractMethod<
    [productId: BigNumberish, docType: BigNumberish],
    [
      [string, string, bigint] & {
        cid: string;
        uploadedBy: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isProductComplete"
  ): TypedContractMethod<[productId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCarbonEmission"
  ): TypedContractMethod<
    [productId: BigNumberish, totalEmissions: BigNumberish, unit: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "storeDocument"
  ): TypedContractMethod<
    [productId: BigNumberish, docType: BigNumberish, cid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DocumentStored"
  ): TypedContractEvent<
    DocumentStoredEvent.InputTuple,
    DocumentStoredEvent.OutputTuple,
    DocumentStoredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DocumentStored(uint256,uint8,string,address)": TypedContractEvent<
      DocumentStoredEvent.InputTuple,
      DocumentStoredEvent.OutputTuple,
      DocumentStoredEvent.OutputObject
    >;
    DocumentStored: TypedContractEvent<
      DocumentStoredEvent.InputTuple,
      DocumentStoredEvent.OutputTuple,
      DocumentStoredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
