/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyToken__factory } from "./MyToken__factory";
export { TradeDocuments__factory } from "./TradeDocuments__factory";
